name: app

type: php:8.0

runtime:
    extensions:
        - ctype
        - iconv
        - apcu
        - mbstring
        - sodium
        - xsl
        - blackfire
        - pdo_pgsql
        

variables:
    php:
        opcache.preload: /app/config/preload.php
build:
    flavor: none

disk: 1024

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

mounts:
    "/var": { source: local, source_path: var }

relationships:
    database: "database:postgresql"
    
hooks:
    build: |
        set -x -e

        curl -fs https://get.symfony.com/cloud/configurator | (>&2 bash)
        
        (>&2 symfony-build)

    deploy: |
        set -x -e

        (>&2 symfony-deploy)

crons:
    security-check:
        # Check that no security issues have been found for PHP packages deployed in production
        # See https://github.com/fabpot/local-php-security-checker
        spec: '50 23 * * *'
        cmd: if [ "$SYMFONY_BRANCH" = "master" ]; then croncape php-security-checker; fi

workers:
    messenger:
        commands:
            # Consume "async" messages (as configured in the routing section of config/packages/messenger.yaml)
            start: symfony console --time-limit=3600 --memory-limit=64M messenger:consume async
